### ISSUE TITLE
Regarding the equations used in the paper 

### ISSUE THREAD

**Issue by abhishekr7** [yuhaozhang/summarize-radiology-findings#5]
Sir, I'm facing problems in interpreting the equations presented in the paper at particularly 2 places,

1. In the decoder LSTM eq(2),  
    s < t > =  LSTM(s < t-1 >, y < t-1 > )
    does state (s) refer to a combination of hidden state and memory ([ h , c ]) or just the hidden 
    state (h)
    If it only refers to (h), then it checks out with the fact that the initial state was initialized to the 
    final state of the encoder,
    s0 = hN,
    just wanted to be sure !  
2. In the eq(4),
    a < t > = softmax(e < t >),
    have you deliberately used softmax instead of the traditional way of calculating 
    attentions (averaging e < t > over all time-steps) as it yielded better results?

**Comment by yuhaozhang** [comment]
Hi @abhishekr7, 

Sorry about this late response, but here are my answers:

1. Yes `s` is referred only to `h` here, since in LSTM only `h` is exposed to the outer world, while `c` is only used for internal memory. So `s` is just a different notation for `h` here.

2. I am not sure what you meant by "averaging e < t > over all time-steps", but the attention weights `a` (or pre-softmax `e`) is different for every time step in decoding. So at a time step `t` of decoding, we run a softmax over all N `e`s, where N is the number of input vectors (or number of encoder hidden states).

Hope these are helpful.
